#!/usr/bin/env python3
"""
Regenerate npc_text.manifest.md -- a lightweight index of the chatter file so
agents/tooling can reason about it WITHOUT loading the 300KB+ source into context.

Usage:  python3 talk_text/gen_manifest.py        (run from the ActiveChat/ALE dir)

Emits aggregate structure only (pool/sub-pool counts, entry-shape tallies, the
%token% vocabulary, and line ranges) -- never the chatter text itself.
Requires: pip3 install lupa --break-system-packages
"""
import os, re, sys
from lupa import LuaRuntime

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "npc_text.lua")
OUT = os.path.join(HERE, "npc_text.manifest.md")

text = open(SRC, encoding="utf-8").read()
lines_total = text.count("\n") + 1
bytes_total = len(text.encode("utf-8"))

lua = LuaRuntime(unpack_returned_tuples=True)
M = lua.execute(text)
ltype = lua.eval("type")

FACTIONS = ["shared", "alliance", "horde"]
SUBPOOLS = ["lines", "duos", "groups"]


def count(tbl):
    return int(lua.eval("function(t) return #t end")(tbl)) if tbl is not None else 0


# %token% vocabulary + tag-key vocabulary, scanned over the raw source.
tokens = sorted(set(re.findall(r"%[a-zA-Z]+%", text)))
tag_keys = sorted(set(re.findall(
    r"\b(roles|moods|areas|times|seasons|events|eventWindow|"
    r"notTimes|notSeasons|notEvents|weight|cooldown|chain)\b\s*=", text)))

# Per-pool line ranges: find `<faction> = {` then its `lines/duos/groups = {`.
ranges = {}
src_lines = text.split("\n")
for i, ln in enumerate(src_lines, 1):
    m = re.match(r"\s*(shared|alliance|horde)\s*=\s*{", ln)
    if m:
        ranges.setdefault(m.group(1), i)

rows = []
totals = {sp: 0 for sp in SUBPOOLS}
for fac in FACTIONS:
    pool = M[fac]
    row = {"faction": fac}
    for sp in SUBPOOLS:
        n = count(pool[sp]) if ltype(pool) == "table" else 0
        row[sp] = n
        totals[sp] += n
    rows.append(row)

grand = sum(totals.values())

with open(OUT, "w", encoding="utf-8") as f:
    w = f.write
    w("# npc_text.lua — chatter manifest\n\n")
    w("> Auto-generated by `talk_text/gen_manifest.py`. Do not edit by hand.\n")
    w("> Lets you reason about the chatter pools without loading the source file.\n\n")
    w(f"- Source: `talk_text/npc_text.lua` — **{lines_total} lines, "
      f"{bytes_total:,} bytes (~{bytes_total//1024} KB)**\n")
    w(f"- Returns a table with three faction pools, each `{{ lines, duos, groups }}`.\n")
    w(f"- **{grand} entries total** "
      f"({totals['lines']} lines, {totals['duos']} duos, {totals['groups']} groups).\n\n")

    w("## Entry counts by pool\n\n")
    w("| Faction | lines | duos | groups | approx. start line |\n")
    w("|---|--:|--:|--:|--:|\n")
    for row in rows:
        w(f"| {row['faction']} | {row['lines']} | {row['duos']} | "
          f"{row['groups']} | {ranges.get(row['faction'], '?')} |\n")
    w(f"| **total** | **{totals['lines']}** | **{totals['duos']}** | "
      f"**{totals['groups']}** | |\n\n")

    w("## %token% vocabulary\n\n")
    w("Tokens substituted at render time by `renderTokens` in `npcTalk.lua`:\n\n")
    w("".join(f"`{t}` " for t in tokens) + "\n\n")

    w("## Line-tag keys in use\n\n")
    w("Authoring tags found on entries (parsed by `makeItem`):\n\n")
    w("".join(f"`{k}` " for k in tag_keys) + "\n\n")

    w("## Editing without burning context\n\n")
    w("- Add/edit chatter: open `npc_text.lua` directly — it's the only place lines live.\n")
    w("- Token logic lives in `npcTalk.lua` (`renderTokens`); tags are parsed by `makeItem`.\n")
    w("- After editing, rerun `python3 talk_text/gen_manifest.py` to refresh this file.\n")

print(f"Wrote {OUT}")
print(f"  {grand} entries | lines={totals['lines']} duos={totals['duos']} "
      f"groups={totals['groups']} | {len(tokens)} tokens")
