--[[
World chat content, faction-gated AND typed.
Each faction pool (shared / alliance / horde) has three lists you can extend freely:
  lines  = standalone one-liners            -> spoken by a single random character
  duos   = two-person back-and-forth        -> two fixed speakers alternate A / B / A / B
  groups = group discussions / list threads -> a rotating cast of 4-6 voices, one line each
  shared = broadcast to EVERYONE; alliance/horde = sent only to that faction.
Placeholders work in any line. Core: %zone% %instance% %class% %bg%.
World/flavor: %profession% %activity% %city% %race% %monster% %critter% %boss%
%consumable% %item% %rep% %mount% %spell% %rare% %pvptitle% %title% %emote%
%event% %season% %timeofday% %weather% %shop% %route% %tale% %npc% %currency%
%food% %drink% %tradegood% %companion% %enchant% %toy% %herb% %ore% %gem% %fish%.
Discouraged (player-imitation; see Tone below): %role% %difficulty% %gearscore%.
See README.md or the pools near the top of npcTalk.lua for the full list.

Tone: in-world roleplay chatter spoken by CIVILIANS, GUARDS, VENDORS, and the
occasional road-weary adventurer talking about life in Azeroth. These are NPCs,
NOT an imitation of real players. Do NOT write lines that emulate player
behaviour: no LFG/LFM, no "anyone wanna group?", no gearscore/parse talk, no
auction-house adverts, no raid logistics. Talk about the world, the weather, the
gossip, the work, the rumors -- the texture of a living city -- not about
queueing for content. Keep it grounded in the lore: no real-world references, no
out-of-character meta, no fourth-wall jokes. Humor is welcome, but it should be
the kind a tavern regular would tell, not a forum poster.
]]--

return {

  shared = {
    -- standalone one-liners (single speaker)
    lines = {
      -- Capital-city life & ambiance
      "The city wakes the same way every morning: bells, then bread, then the auctioneers, then the complaining. I love it.",
      "Rain on the cobbles, smoke from the chimneys, lamplight in the windows. The city's at its prettiest when it's grey.",
      "Commons is loud today. Three auctioneers shouting over each other and not one of them selling anything I need.",
      "Stood in the bank line for twenty minutes behind someone reorganizing forty bags. Send patience.",
      "The blacksmith's apprentice dropped a whole rack of swords. The clang echoed three districts over.",
      "Saw a paladin help an old woman carry her groceries across the square. The Light's in the small things too.",
      "Tavern's out of the good ale already. It's not even noon. Rough crowd today.",
      "Someone painted a mustache on the founder's statue overnight. The guards are 'investigating' between laughs.",
      "A traveling merchant set up by the fountain selling 'genuine artifacts.' They're rocks. Nice rocks, though.",
      "The lamplighters are making their rounds. Dusk in the city always feels like a held breath.",
      "Heard two nobles arguing over who has the bigger estate. Neither noticed the pickpocket between them.",
      "Beggar by the gate has better stories than most adventurers. Spare him a copper if you pass.",
      "The city criers have the same news as yesterday. Slow week for villainy, apparently.",
      "I just like sitting in the tavern and listening to other people's adventures. Cheaper than having my own.",
      "Rumor in the market: a noble's wedding next week. Half the city's invited, the other half is catering.",
      "A child asked me if I'd ever seen a real dragon. I said yes. Made their whole week.",
      "Bought a meat pie from a street cart. Didn't ask what's in it. Some city mysteries are better left alone.",
      "Two old veterans arguing about a war that ended before I was born. I bought them both a drink.",
      "The street musician outside the inn only knows one song, but he plays it with his whole heart.",
      "City guard stopped me to ask directions. To his own barracks. New recruit, bless him.",
      "The watch doubled the patrols near the bank. Either trouble's brewing or someone important's visiting.",
      "A guard recited the entire city ordinance to a drunk who just wanted to find the privy. Justice.",
      "They post the wanted notices by the gate. Same three rogues every week. Practically celebrities now.",
      "The city tailor does the finest stitching in the kingdom. Pricey, but you'll never look like a peasant again.",
      "Innkeeper set my hearthstone and then asked if I wanted the usual. I have a usual now. I've arrived.",
      "The stablemaster knows every pet in the city by name. Mine she calls 'the troublemaker.' Accurate.",
      "Flight master's gryphons are restless today. Storm coming, he reckons, and he's never wrong.",
      "Stood in the forge watching the blacksmith work for an hour. There's poetry in good steelwork.",
      "Fruit vendor gave me an extra apple 'for the road.' Small kindness, big city, good day.",
      -- Faction-neutral hubs (Dalaran, Shattrath, Booty Bay)
      "Dalaran floats over Crystalsong today. Best view in Northrend, if you don't mind the cold.",
      "The Legerdemain Lounge has a fire going and someone playing piano. Perfect place to wait out a blizzard.",
      "Antonidas Memorial fountain is full of coins from a hundred wishes. Mages wish big, apparently.",
      "Watched an apprentice mage misfire a portal and end up in the sewers. We've all been there.",
      "The streets of Dalaran are neutral ground. Doesn't stop the glaring, though.",
      "Lower City in Shattrath is a melting pot. Heard six languages before I finished my soup.",
      "The Aldor and Scryers still won't share a tavern. Old grudges die hard in Shattrath.",
      "A naaru's light fills the Terrace of Light. Whatever your faith, it's hard not to feel it.",
      "Refugees still arrive in Shattrath daily. The Sha'tar take them all in. Every one.",
      "Booty Bay never closes. Goblins don't sleep when there's a copper to be made.",
      "A goblin in Booty Bay sold me a map to buried treasure. The treasure was another map. Well played.",
      "The Salty Sailor Tavern is rowdy tonight. Two duels and a marriage already, and it's not even dark.",
      "Steamwheedle goblins are neutral, sure. Neutral about everything except your gold.",
      "Northrend wind cuts right through Dalaran's streets. Thank the Light for that lounge fireplace.",
      -- War, the wider world, rumor
      "Word from the front: the Lich King's grip on the north hasn't loosened. Pray for our soldiers in Icecrown.",
      "They say the dragons gather in Wyrmrest. When dragons hold council, the rest of us should worry.",
      "Heard the Argent Crusade is recruiting at the city gates. Noble cause, terrible retirement plan.",
      "A traveler from Northrend says the Scourge is quieter lately. Quiet Scourge is the scary kind.",
      "The Cenarion Circle warns the Emerald Dream is troubled. Druids look tired. That's never good.",
      "Tirion Fordring's name on every soldier's lips heading north. If anyone can end this, it's him.",
      "They say the King hasn't slept in days. Heavy is the head, and all that.",
      "Heard the Stockades had a breakout. Probably just a drunk who wandered in the wrong door again.",
      "The harbor's foggy today. Half the dock workers swear they saw a ghost ship. Half are just hungover.",
      "Politics in the capital again. Everyone's got an opinion, nobody's got a solution.",
      "They say peace talks failed again. The diplomats go home, the soldiers stay in the field. Same as always.",
      "Two faction banners flying over the same contested town by week's end. Bet the goblins are selling both.",
      "Saw an Alliance and a Horde soldier nod at each other in neutral Dalaran. War's complicated, ain't it?",
      "Heard a human and an orc came to blows in Booty Bay. The goblin bartender charged them both for the broken table.",
      "Did you all hear about the guild leader from Vanquished who vanished with the whole treasury?",
      "A hooded figure's been buying every candle in the city for three days. Cult, or just bad at planning a party.",
      "They say there's a door in the canals that wasn't there last week. Nobody's opened it. Yet.",
      "Rumor of a secret tavern beneath the city that only serves those who know the password. I do not know the password.",
      "Someone's leaving fresh flowers at the unmarked grave in the cemetery every dawn. No one's caught them.",
      -- Festivals & holidays
      "Brewfest decorations are going up in the cities already. My liver is filing a formal complaint.",
      "The Darkmoon Faire's back. I've already lost my month's gold to a goblin and a ring toss.",
      "Hallow's End bonfire in the square tonight. Bring a costume, leave with candy and a headache.",
      "Winter Veil lights are up across the city. Greatfather Winter had better bring me that mount this year.",
      "Lunar Festival fireworks over the city. The elders are handing out Coins of Ancestry. Grab a fistful.",
      "Pilgrim's Bounty feast in the city square. The tables go on forever. So does the line.",
      "Love is in the Air and the city's drowning in pink. I've been handed nine perfumes and zero proposals.",
      "Children's Week. The orphans are touring the city and every single one waved at me. My heart.",
      "Midsummer flames lit in every capital tonight. Dancing till dawn, win or lose the bonfire war.",
      "Noblegarden eggs hidden all over the city and grown adults are SPRINTING for them. No shame. None.",
      "Day of the Dead shrines went up in the cemetery. Marigolds everywhere. The dead are remembered well here.",
      -- Faith, the elements, quiet moments
      "Lit a candle in the Cathedral for a friend who didn't come back from the north. The Light keeps them now.",
      "Knelt at the moonwell and felt the day's weight lift a little. Elune's mercy is real, whatever you believe.",
      "The shaman say the elements are restless lately. I'm no shaman, but even I can feel the air's gone strange.",
      "Sat in the silence of the Terrace of Light until the naaru's glow felt like an answer. Maybe it was.",
      "Saw a knight teaching a farmboy to hold a sword properly. Everyone starts somewhere.",
      "An old mage feeds the city pigeons every morning at the fountain. Says they're better company than apprentices.",
      "The orphanage matron walked a line of children through the city. They waved at every guard. Every one waved back.",
      "A blind old man asked me to describe the sunset over the harbor. Best ten minutes of my whole week.",
      "Gave my cloak to a shivering kid by the gate. The cold's worth it. I've got a warm inn to walk to.",
      "A stranger returned my dropped coin purse, full. Faith in folk: restored, at least till the auction house.",
      "The tavern keeper remembered my late friend's usual order and poured it without a word. Kindness has a long memory.",
      -- Bards, music, small wonders
      "A bard just made up a song about my last dungeon run. Got the details wrong but the chorus slaps.",
      "Street drummers set up in the square and within minutes half the city was dancing. Magic, the ordinary kind.",
      "An old troll played a flute carved from a raptor bone. Loveliest, eeriest sound I've ever heard.",
      "Saw a painter capture the whole harbor at sunset in twenty quick strokes. Bought it on the spot.",
      "The opera house reopened. Tickets sold out in an hour. The dragon's not even in this production. Probably.",
      "Two bards in the same tavern turned a song into a sing-off. The crowd picked sides. It got beautifully out of hand.",
      "The inn cat has claimed the warmest chair by the fire and the entire city respects its authority.",
      "A stranger paid my tab and vanished before I could thank him. Pay it forward, the bartender said. So I will.",
      -- Races rubbing shoulders
      "A dwarf told me his beard was older than my entire bloodline. He wasn't wrong and he knew it.",
      "Watched a tauren gently move out of a gnome's way in the bank. Big folk, bigger hearts.",
      "A draenei diplomat tried to explain the Light to a Forsaken. Long conversation. Surprisingly polite.",
      "A night elf rolled her eyes at a human's 'ancient' family history. Ten thousand years is a long time to gloat.",
      "A blood elf and a high elf passed in Dalaran without a word. Family reunions are awkward.",
      "Every city's got its own smell. Orgrimmar's smoke, Ironforge's ale, Darnassus's flowers. Home is whichever's closest.",
      "Crossed half of Azeroth this week and the friendliest face was a goblin who overcharged me with a smile.",
      -- Mounts, pets, the little chaos
      "Some noble paraded his new mechanostrider through the square. It backfired. The crowd loved it.",
      "A little girl asked to pet my war mount. The mount that has killed dragons now lives for ear scratches.",
      "Someone's pet sporebat is loose in the auction house and honestly it's improving the place.",
      "Saw a goblin propose with a ring he 'definitely didn't' lift from the auction house. She said yes anyway.",
      "A gnome ran past me in the street yelling 'IT'S SUPPOSED TO DO THAT.' Nothing was supposed to do that.",
      "A dwarf and a gnome arguing engineering in the street drew a bigger crowd than the actual parade.",
      "Rumor says someone slew Onyxia again last night. Her head's hanging in the city gate. Again. Poor girl.",
      -- The road, the traveler's life
      "Met a fellow traveler in the inn. Swapped stories till the candles burned out. That's the real endgame.",
      "Some nights the city feels too big and lonely. Then a stranger shares a joke and it's home again.",
      "A rainstorm rolled into the harbor and the whole city ducked into the taverns. Crowded, cozy, perfect.",
      "I've slain dragons and saved villages, but I still can't navigate the bank line without an existential crisis.",
      "Funny how the safest I ever feel is standing in a crowded city square doing absolutely nothing important.",
      "A whole life happens in these streets between dungeon runs. Weddings, funerals, arguments over fish prices. The real epic.",
      "The city's loud and crowded and overpriced and somehow it's the only place that ever feels like coming home.",
      "Watched the gates close for the night from the top of the wall. Whole city tucked in safe behind stone. Sleep easy.",
      "Whatever banner flies over it, a city is just people trying to get home before dark. Easy to forget that.",
      "Long day. Found a quiet bench, a warm drink, and a good view of the city lights. That'll do. That'll do just fine.",
      -- A light sprinkle of in-character grouping calls (RP-flavored, not spam)
      "A %role% by the gate is gathering brave souls for a delve into %instance%. Glory promised, survival not guaranteed.",
      "Anyone in the city up for a wander to %zone%? Tired of these crowded streets.",
      "%role% sitting in the tavern, bored, will travel for adventure. Whisper me.",
      "Heading out of the city to %zone% at sundown. Walking the long way for the scenery. Join if you like.",
      "Anyone want to escort a nervous %class% through %zone%? First time out of the city.",
      "Quiet night in the city. A %role% looking for a chat and maybe a quick delve. Either's fine.",
      "Word's gone round the tavern that %instance% has stirred again. They're asking for a %role% and a steady blade.",
      "A caravan's forming at the gate, bound through %zone%. They want a %class% or two for the rough stretches.",
      -- Street-vendor & guard cries (in-character flavor)
      "Fresh apples, ripe melons, honeyed dates! Best produce in the city, ask anyone, mostly my cousin!",
      "Sharpening blades by the smithy gate, two copper a sword, keen as a widow's tongue!",
      "Hot pies! Meat pies, fruit pies, mystery pies! The mystery ones are half price and twice the adventure!",
      "Candles, lanterns, lamp oil! Don't let the night catch you dark, friends!",
      "Bandages and salves, battle-tested! If they didn't work I'd be out of business AND blood!",
      "Maps! Real maps! Get where you're going before the goblins sell you a fake one!",
      "Charms and trinkets, lucky every one! Worked for me, and look how I turned out! ...don't look too hard.",
      "Fine cloth, dyed in the city's own vats! Wear color like you mean it!",
      "Cold ale, warm bread, a place by the fire! The inn's door is open, traveler!",
      "Songs for a copper, stories for a silver, the truth for a gold piece I haven't got!",
      "Repairing armor by the bank! Dents hammered, straps mended, dignity not included!",
      "Spices from across the sea! Make your trail rations taste like something other than regret!",
      "Pet food, pet toys, pet everything! Spoil the only companion who never asks for a cut of the loot!",
      "Keep it moving by the gates, folks, the caravan needs the road. Plenty of city to stand around in.",
      "No dueling in the bank line. I don't care who started it. Take it to the ring like civilized warriors.",
      "Curfew bell's rung. Honest folk to their beds, the rest of you to wherever you sleep. Move along.",
      "Lost a child? Check the fountain. They always end up at the fountain. Every time. Like little homing pigeons.",
      "Mind the wet cobbles by the harbor. Lost a recruit to a comedic slip just this morning. He's fine. His pride isn't.",
      "Move it along, citizen. Yes, you, admiring the statue for the fortieth time. It'll still be bronze tomorrow.",
      -- Overheard half-conversations (the "..." flavor)
      "...so I told the auctioneer, that's not a deal, that's a robbery with extra steps...",
      "...and THEN the gryphon wouldn't land, so I'm just circling the city going 'down, DOWN, you feathered menace'...",
      "...swear on my beard the fish was THIS big before it got away...",
      "...no, see, the trick to the bank is you go at dawn, before the whole city wakes up...",
      "...she said yes! At the moonwell, with the bard and everything! I'm getting MARRIED...",
      "...third time I've been turned into a sheep this week, I'm starting to take it personally...",
      "...best stew in the city, hands down, don't let the harbor folk tell you otherwise...",
      "...you didn't hear it from me, but the noble in the blue cloak owes half the market money...",
      -- Closers
      "The city wakes the same way every morning and I wouldn't trade a single bell of it.",
      "A capital is a promise that tomorrow there'll still be a market, a bell, a warm inn. Worth fighting for, that promise.",
      "Spent the whole day just being a person in a city full of people. No quests, no loot, no dragons. Best day in ages.",
      "Some come to the city for the bank, some for the auction house, some for the war. I come for the bread. No regrets.",
      "Last call at the inn, lamps going dim, the city settling into sleep. Goodnight, capital. Same time tomorrow.",
      -- Lines using the expanded placeholders (%city% %race% %profession% %boss% %mount% etc.)
      "Word from %city% is a %race% finally put %boss% down for good. The taverns will be loud tonight.",
      "Anyone in %city% leveling %profession%? I'll trade mats for a few crafts, paying fair.",
      "Saw a %race% %class% ride past on %mount%. Stopped half the street just to stare.",
      "They say %rare% was spotted out in %zone% again. Every hunter in %city% is already saddling up.",
      "Just hit revered with %rep%. The grind was long but the rewards are finally worth it.",
      "Some %class% in %city% is selling %item% for %gold%. Either a fortune or a fool, can't tell which.",
      "Half of %city% started to %emote% when the news came in. You love to see it.",
      "Fresh %level% today and proud of it. Onward to the next.",
      "Don't step into %instance% on %difficulty% without %consumable% in your pack. Learned that the hard way.",
      "Watched a %race% land %spell% perfectly at the last second. Clutch doesn't begin to cover it.",
      "Earned the title '%pvptitle%' this week. Wearing it everywhere, even to the bank.",
      "LFM %instance% %difficulty%, link %gearscore% gearscore and a %role% spec, summons from %city%.",
      -- Ambient flavor: events, seasons, time of day, shops, routes, tales, weather
      "%event% has %city% packed wall to wall. Couldn't get a table at %shop% to save my life.",
      "Nothing beats %timeofday% in %zone% when there's %weather% rolling in.",
      "%season% always makes me restless. Half a mind to take %route% and just see where it goes.",
      "Stopped at %shop% for a pint and ended up hearing the whole tale of %tale%. Worth the detour.",
      "Took %route% at %timeofday% and the view was unreal. Recommend it to anyone passing through.",
      "The old-timers at %shop% still argue about %tale% like it happened yesterday.",
      "%weather% over %zone% this %timeofday%. Beautiful and miserable in equal measure.",
      "They're decorating %city% for %event% already. The %season% air and the lanterns... it's a good time to be alive.",
      "A %race% %class% just strolled through %city% with %item% on their back like it was nothing. Some people have all the luck.",
      "Watched a %class% drop %spell% in the middle of the square just to show off. Half of %city% stopped to %emote%.",
      "Word is someone finally tracked down %rare% out in %zone%. Took them a %season% of camping, but they got it.",
      "Saw a %race% ride past on %mount% today and the whole street went quiet. Some things you just have to %emote% at.",
      "Anyone running %instance% %difficulty% tonight? I'll heal, I'll tank, I'll carry your bags — just get me out of %city%.",
      "Hit exalted with %rep% this %timeofday%. Took half a lifetime and more %gold% in repairs than I'll admit.",
      "Some %level% %class% asked me how to get to %zone%. Friend, you are very far from where you ought to be.",
      "The %profession% trainer in %city% says %consumable% is selling for %gold% a stack now. Highway robbery.",
      "Met a veteran who earned the title '%pvptitle%' the hard way. Bought him a round at %shop% and just listened.",
      "Someone soloed %boss% at %gearscore% gearscore and won't stop talking about it. Honestly? Fair enough.",
      "%weather% rolling in over %zone% at %timeofday%. The caravans on %route% are going to have a miserable night.",
      "Old sailor at %shop% swears he saw %rare% from the deck off %zone%. Three drinks deep, mind you.",
      "Anyone got %consumable% to spare before the %instance% run? I'll trade %gold% or a favor, your call.",
    },
    -- two-person back-and-forth (speakers alternate A / B)
    duos = {
      {"Is %gearscore% gearscore enough for %instance% on %difficulty%?", "More than. Bring %consumable% and you're set.", "Saving you a spot. Summon's up in %city%."},
      {"A %race% just outbid me on %item% by %gold%.", "Ruthless. The auction house in %city% is a battlefield.", "I'll get the next one. Or I'll cry. Possibly both."},
      {"How do night elves get anywhere in this city? It's all bridges and trees.", "Slowly, and with great elegance.", "Mostly we just fall and call it 'shadowmelding'."},
      {"Got turned into a sheep for brawling in Dalaran again.", "The Kirin Tor warned you.", "Worth it. Baa."},
      {"Aldor or Scryers, which do you side with?", "Whichever's offering the better rewards this week.", "A diplomat, I see."},
      {"Is it safe to walk the Booty Bay docks at night?", "Define 'safe.' Define 'walk.' Define 'night.'", "...I'll take a guard."},
      {"Do you ever just stop and appreciate how beautiful these cities are?", "Between the wars and the auction house? Rarely. But yeah, sometimes.", "Sometimes is enough."},
      {"New in the city. Any advice?", "Don't trust goblins, don't insult anyone's mother, and tip the bard.", "...and never split the loot in a crowded tavern."},
      {"Bartender, what's good tonight?", "The ale, the stew, and the company. In that order.", "I'll take all three and a story to go."},
      {"For the Alliance!", "For the Horde!", "For the love of- can we NOT do this in the bank line?"},
      {"Move along, citizen.", "I live here.", "...Move along anyway. It's been that kind of shift."},
      {"Did you hear what happened in Theramore?", "Don't. Just... don't. Not today.", "Aye. Pour one out."},
      {"Why's everyone gathered in the square?", "Public hanging.", "...of a really bad street mime, but still, drama."},
      {"First time in the big city. It's... a lot.", "You'll get used to it. Stick to the main roads and trust your gut.", "And never, ever follow a goblin into an alley."},
      {"Gnomes and goblins should NOT be allowed to do engineering in the same city.", "Agreed. The last 'demonstration' took out a city block.", "In their defense, it was a very impressive city block."},
      {"Why are trolls always saying 'mon'?", "Why are humans always saying 'epic loot'?", "...fair point, mon."},
      {"Is it just me or are there too many people summoning mounts INSIDE the bank?", "It's not just you.", "Someone's kodo is currently blocking the entire auction house."},
      {"Met someone in the tavern last night.", "Adventurer?", "Baker, actually. Real trade, steady hands, makes incredible bread. I'm smitten.", "Marry the baker."},
      {"How long have you been sitting in this tavern?", "What day is it?", "...that long, huh."},
      {"Why is the line at the bank so long?", "Tax season.", "Even with a war on, there's taxes?", "ESPECIALLY with a war on."},
      {"Who keeps dueling right outside the bank?", "Same two warriors every day.", "At this point it's less a rivalry and more a marriage."},
      {"Why does every tavern have that one drunk who challenges everyone to a duel?", "Tradition.", "He's undefeated because nobody takes him seriously enough to fight."},
      {"You ever just stand in the capital and watch everyone rush by?", "All the time. Everyone's the hero of their own story.", "And here we are, two faces in a thousand of them.", "Best seat in the house, if you ask me."},
      {"They're raising the bridge for a ship. We'll be stuck on this side for an hour.", "Tavern's right there.", "...I've never loved a delayed bridge more in my life."},
      {"Lost my whole coin purse to the auction house today.", "Buying or selling?", "Buying. I had a plan.", "You always have a plan. That's the problem."},
      {"Is the city always this loud?", "Only when it's awake. Come back before dawn, it's a different world.", "I'll take your word for it. I value sleep."},
      {"Heard the King's holding court today.", "Good luck getting near the keep. Whole city turned out.", "I just want to deliver my cabbages.", "The cabbages will have to wait for the realm, friend."},
      {"You're out late.", "Couldn't sleep. The city's quieter now. I like it.", "Aye. The night's the only time this place stops shouting.", "Then let's not waste it talking. Mind the view a while?"},
      {"What's that crowd by the docks?", "Sailor came back with a tale and a sea monster's tooth.", "Real tooth?", "Real enough for the price of his next three drinks."},
      {"You from around here?", "Born three streets over. Never left. Never wanted to.", "Must be nice, having one place be home.", "It is. Stay a while. The city grows on you."},
      {"Meet you by the city fountain in five.", "Which fountain? There's like four.", "The one where we always meet.", "...right. The one with the pigeon that hates me. Got it."},
      {"Is the city always this crowded at festival time?", "This is a quiet day.", "...I need to lie down.", "Tavern's right there, friend. Welcome to the capital."},
      {"You buying or selling at the auction house?", "Browsing.", "Nobody just 'browses' the auction house.", "...fine. Spending money I don't have on things I don't need. Happy?"},
      {"How's business at the stall today?", "Slow. Everyone's saving coin for the festival.", "I'll buy something to break your streak.", "Bless you, that's why I keep the corner stall."},
      {"Officer, someone stole my coin purse!", "Was it a goblin?", "...maybe?", "Then it's gone, friend. Light keep it. Want directions to the bank instead?"},
      {"Did you HEAR what happened at the keep?", "No, what?!", "...I don't actually know, I was hoping you did.", "...we are terrible at gossip."},
      {"Heard the dragons are stirring up north.", "They're always stirring. Scaly drama merchants, the lot of them.", "Say that louder. See if Alexstrasza's listening.", "...suddenly I have somewhere else to be."},
      {"Why's that paladin been kneeling in the Cathedral since dawn?", "Lost his whole company in the north. The Light's all he's got left.", "...I'll light a candle and leave him be.", "That's the kindest thing you can do."},
      {"Think the war'll ever actually end?", "Wars end. Then somebody finds a new reason. Always do.", "Cheerful.", "I'm a realist with a drink in my hand. Same thing some nights."},
      {"That orc and that human have been arm-wrestling for an hour.", "In neutral Booty Bay, no less.", "Goblin's taking bets on both.", "Goblin always wins, then. The only true neutral party."},
      {"LFM %instance% %difficulty%, need a %role%. %gearscore%+ and bring %consumable%.", "Summon from %city%?", "Aye, soon as we've a %class% for the last slot.", "On my way. Don't pull %boss% without me, I mean it."},
      {"Is it worth grinding %rep% all the way to exalted?", "Depends. The %mount% at the end is worth more than %gold% to the right buyer.", "Sold. I'll start the %profession% dailies this %timeofday%.", "Pace yourself. That rep broke better folk than us."},
      {"Camped %zone% for %rare% three nights running.", "Still nothing?", "Nothing but %weather% and regret.", "It'll spawn the moment you log to sleep. They always do.", "...you're right and I hate it."},
      {"Bard at %shop% is taking requests.", "Ask for the ballad of %tale%.", "Too sad for a %season% night, surely.", "That's exactly why. A good dirge and a warm pint — best %timeofday% you can buy.", "...go on then. Make us weep into the ale."},
      {"A %race% %class% just walked in wielding %item%.", "The real one?", "Glows like a dropped star. Either it's real or it's the best forgery in %city%.", "Buy them a drink and find out. Subtly.", "There is nothing subtle about you."},
      {"How'd the %instance% run go?", "We wiped on %boss% six times, then a %class% dropped %spell% and it just... clicked.", "%difficulty%?", "%difficulty%. We were underleveled and overconfident.", "The two great traditions of this realm. Drinks on me."},
      {"Took %route% out to %zone% for the %event% festivities.", "Worth the trip?", "%weather% the whole way, but the lanterns at the end? Worth every copper.", "And the %gold% you spent on trinkets, no doubt.", "...the festival economy is a predator and I am its prey."},
    },
    -- group discussions (many voices, rotating cast of 4-6)
    groups = {
      {"Settle it for me: which capital is the finest in all Azeroth?", "Ironforge. Warm stone, endless ale, and the Great Forge never goes cold.", "Stormwind. Spires like they're carved from morning light. Nothing finer.", "Darnassus, easily. You've clearly never lost an hour to moonlight on the ponds.", "Thunder Bluff. Open sky, clean wind, and not a single auctioneer screaming in your ear.", "Silvermoon. Ten thousand years of refinement, and it shows in every gilded arch.", "Undercity, if you've the stomach. Grim, yes, but the Forsaken made a home out of grief.", "You're all wrong. Booty Bay. No rules, great fishing, and the ale's only mostly poisoned.", "...of course the goblin lover says Booty Bay.", "It has a SUNSET over the SEA. What's your spire got? Pigeons.", "Every one of you is loyal to wherever your hearthstone's set. Admit it.", "Fair. Home's home. Mine just happens to be the prettiest."},
      {"Anyone else feel the cities are quieter since the call-up north?", "Half the regulars from my tavern shipped to Icecrown. Place feels hollow.", "The recruiting officers are at every gate. Argent Crusade, mostly.", "My brother signed on. Said someone has to. I couldn't argue.", "Noble cause. Terrible odds. The Scourge doesn't tire and doesn't grieve.", "They say Fordring himself is leading the push. If anyone can, it's him.", "I just hope the ones who go come back. Most of them. Some of them.", "Light keep them. Earth Mother hold them. Whatever you pray to, pray it loud.", "...and keep their stools warm at the tavern. They'll want them back.", "That's the most hopeful thing anyone's said all week. I'll drink to it."},
      {"What's the strangest thing you've seen in a city square?", "A goblin auctioning 'genuine dragon eggs.' They were painted gourds. He made forty gold.", "A fully armored knight playing hopscotch on a chalk grid. Very seriously. On his way to war.", "Two bards turned a song into a duel. The crowd took sides. Beautiful chaos.", "A street preacher's been shouting about the end times for a week. The end times are taking their time.", "A stray dog adopted the entire city guard. They take turns feeding it. It eats better than I do.", "An apprentice mage misfired a portal and dropped straight into the sewers. We've all been there.", "A noble's carriage stuck in the market crowd, so he had to walk like the rest of us. The street rejoiced.", "A tauren gently lifting a lost gnome onto his shoulder so the little one could find his friends. Made my year.", "...this city is a circus with a war on the side, and I love every cobblestone of it.", "Couldn't have said it better. Same time tomorrow at the fountain?"},
      {"Settle a bar bet for us: hardest %boss% ever put down?", "%boss%, no contest. We threw ourselves at it for a whole %season%.", "Soft. Try it at %difficulty% with a pickup group and %consumable% running low.", "You're both wrong. The hard part was the trash before %boss%, not the boss.", "The hard part is always the %class% who stands in the fire. Every group has one.", "...we ARE the %class% who stands in the fire, aren't we.", "To standing in the fire. May we one day learn to step out of it.", "Drinks at %shop%. We've earned the wipe stories."},
      {"If you could own one thing in all Azeroth, what'd it be?", "%item%. I'd never set it down, not even to sleep.", "%mount%. Ride into %city% on that and you never pay for a drink again.", "Pfft. The title '%pvptitle%'. You can't buy what you bleed for.", "%gold% in the bank and a quiet cottage in %zone%. That's the dream.", "Exalted with every %rep% there is. Just to say I did it.", "...all of you chasing legends, and here's me just wanting a stall that sells out by %timeofday%.", "Honestly? That's the wisest answer at this table.", "To small dreams, then. They're the only ones that come true."},
      {"What's the worst luck you've had on a drop?", "Ran %instance% every week for a %season% and %boss% never once gave up %item%.", "Lost %item% to a %class% on a single dice roll. Off by one number.", "Sold a green for %gold%, then watched it resell for ten times that an hour later.", "Tracked %rare% across half of %zone%, dismounted to loot, and a passing %class% sniped it.", "...we are a table of the unluckiest souls in %city%, aren't we.", "And yet here we all are, still rolling. Still hoping.", "That's adventuring, friend. The Light gives, the dice take."},
    },
  },

  alliance = {
    -- standalone one-liners (single speaker)
    lines = {
      "Cathedral Square is quiet this morning. The Bishop's sermon must have run long again.",
      "Anyone else stop to watch the Stormwind guards change shift at the Trade District gates? Best free show in the city.",
      "The smell of fresh bread from the Trade District bakery is the only buff I need today.",
      "Pickpockets in Old Town again. Keep a hand on your coin purse near the Slaughtered Lamb crowd, friends.",
      "Sitting by the Stormwind canals watching the boats. Days like this make the wars feel far away.",
      "Mage Quarter portals are down again. Whoever's on duty, the line is out to the fountain.",
      "Just adopted a cat from the Cathedral district. Named him Bolvar. He judges everyone.",
      "Selling fresh-cut tulips from the Stormwind gardens! Brighten your keep, three silver a bunch.",
      "A fine day for a stroll through the Dwarven District. The forges are warm and the ale is warmer.",
      "Lost in the tram tunnels between Ironforge and Stormwind. Send a map. And a snack.",
      "They keep the Great Forge burning so bright you forget it's snowing in Dun Morogh.",
      "Sat by the Darnassus ponds and lost an hour to the moonlight on the water. No regrets.",
      "A Sentinel told me the leaves of Teldrassil never truly stop whispering. I believe her.",
      "The owls of Darnassus hooted all night. Either an omen or they're just owls. Probably owls.",
      "The crystals of the Exodar sing when the light hits them right. The draenei call it home now.",
      "The Exodar still tilts a little where it crashed. They say you get your sea legs eventually.",
      "Anchorites at the Exodar bless travelers for free. Took the blessing, felt great, fell off a ramp anyway.",
      "Made the full tour today: Stormwind to Ironforge by tram, Ironforge to Darnassus by boat. My feet are retired.",
      "A new adventurer asked me how to get to Stormwind from the night elf lands. Friend, clear your afternoon.",
      "First snow in Dun Morogh and the whole of Ironforge smells like mulled cider. Best time of year.",
      "Stormwind in spring, the gardens in full bloom. Even the guards crack a smile.",
      "Autumn leaves drifting down off Teldrassil into the Darnassus ponds. Bittersweet and beautiful.",
      "The Mage Quarter at night is all blue light and quiet humming. Easy to forget there's a war on.",
      "Old Town never really sleeps. The rogues just change shifts with the night watch.",
      "The Trade District at high noon is pure chaos. Auctioneers, beggars, nobles, and me, hopelessly lost.",
      "Cathedral District is the only quiet corner of Stormwind. I go there just to hear myself think.",
      "Two elves slow-dancing by the Darnassus moonwell while a bard played. The whole square went quiet.",
      "An anchorite blessed my journey and meant it. You can tell when someone means it.",
      "Anyone up for a scavenger hunt in Stormwind? First clue is 'Where the King's Shadow Lies.'",
      "Forming a casual band at the Stormwind gates, bound for %instance%. No pressure, just good company.",
      "Looking for a few brave souls at the Ironforge gates for a run to %instance%. Beards optional.",
      "Standing at the Darnassus portal forever. Is ANYONE going to %zone% today?",
      "The Stormwind fountain is NOT a wishing well, a swimming pool, OR a bath, and yet here we all are.",
      "Stormwind's spires catch the morning light like they're made of it. Pride of the Alliance, and rightly so.",
      "Ironforge has stood since before the stories started. Let the surface squabble; the mountain endures.",
      "Found a bookshop tucked behind the Mage Quarter. Smells of dust and old magic. I may never leave.",
      "Eyes open near Old Town tonight. Word is the thieves' guild is feeling ambitious. Aren't they always.",
      "A %race% %class% rode into the Trade District on %mount% and the gnome children lost their minds. Can't blame them.",
      "The %profession% trainer in Ironforge says she'll teach me to craft %item% one day. One VERY distant day.",
      "Cathedral's blessing every soldier bound for %zone% this %timeofday%. The Light go with them, every one.",
      "Some %level% %class% asked the way to %zone% in the Mage Quarter. Took the portal mage twenty minutes to stop laughing.",
      "Heard a Stormwind veteran earned '%pvptitle%' on the Wintergrasp wall. Bought him a pint at the Pig and Whistle and just listened.",
      "LFM %instance% %difficulty% forming at the Stormwind gates. Need a %role%, %gearscore%+, bring %consumable%.",
      "Saw a Sentinel back from %zone% with %item% still wet from the fight. Darnassus turned out just to watch her pass.",
      "Hit revered with %rep% today. The Ironforge quartermaster finally smiled at me. First time in a %season%.",
      "%weather% over Dun Morogh this %timeofday%. The tram's running slow and the whole of Ironforge smells of wet beard.",
      "A dwarf at the Stonefire Tavern swears he wrestled %rare% in the Hinterlands. Sober, he tells it shorter.",
    },
    -- two-person back-and-forth (speakers alternate A / B)
    duos = {
      {"The Lion's Pride Inn is packed tonight.", "It's the bard. He actually learned a second song.", "Two whole songs? Practically a symphony."},
      {"Why is there a gnome statue in the middle of Stormwind?", "Knowledge, valor, and exceptionally good engineering, my friend.", "It's so we always look up to the little folk."},
      {"Anyone know why the Ironforge gryphons look so smug?", "They get to leave whenever they want. Wouldn't you be smug?"},
      {"Best enchanter in the city? Asking for my very plain weapon.", "Old elf in the Mage Quarter. Charges a fortune, glows like a star.", "Worth it. My sword now has a personality."},
      {"Did you see the lights over the Mage Quarter last night?", "Probably an apprentice's experiment.", "It spelled out a name. THAT'S not an experiment."},
      {"First day with the city guard. Any tips?", "Stand up straight, learn the streets, and never chase a rogue into Old Town alone.", "Also the Mage Quarter sells the good coffee. You'll need it."},
      {"They say the King's planning another push north.", "Then Light help the lads who march. Icecrown takes more than it gives back.", "...I'll keep a candle lit in the Cathedral for them.", "We all will."},
      {"Teldrassil feels heavier lately, doesn't it?", "The Sentinels say the wilds are troubled. The leaves whisper louder.", "Or it's just the wind.", "...in ten thousand years, has it ever been 'just the wind' here?"},
      {"Did you catch that %race% %class% wielding %item% in the Trade District?", "Off %boss%, no less. %difficulty%.", "...and here's me still saving %gold% for a decent %profession% recipe."},
      {"%weather% over Dun Morogh again. The tram's crawling.", "Take %route% instead?", "In this %season%? I'd sooner wait. Pull up a stool at %shop% and we'll outlast it."},
      {"Exalted with %rep% at last. The %mount% is mine.", "How long did THAT take?", "Most of a %season% and more repair %gold% than I'll ever admit to my spouse."},
    },
    -- group discussions (many voices, rotating cast of 4-6)
    groups = {
      {"Which corner of Stormwind is the best to just sit and waste an afternoon?", "The canals, no contest. Watch the boats, feed the gulls, forget the war exists.", "Cathedral Square. Quietest spot in the whole city. I go there to think.", "The Trade District, if you like chaos. Best people-watching in the Alliance.", "Old Town, if you don't mind the company. The rooftops at dusk are something else.", "The Dwarven District. Warm forge, cold ale, and a dwarf who'll tell you his whole life story.", "...you've all forgotten the gardens in the Mage Quarter in spring.", "Light, you're right. The gardens. Lost a whole afternoon there last week.", "That's the secret, isn't it. This city's full of corners worth losing an afternoon to."},
      {"LFM %instance% %difficulty%, summon's at the Stormwind gates.", "Need what?", "A %role% and a %class% who knows the %boss% fight.", "%gearscore% and I've got %consumable% for the whole run.", "Invite's up. Mind the Cathedral bells, we move when they toll."},
      {"Worth grinding %rep% out of Ironforge?", "The %mount% alone is worth more than %gold%, aye.", "And the %profession% recipes you can't get anywhere else.", "Then I'll run the dailies till my gryphon knows the way by heart.", "It will. Mine flies to the quartermaster without me even asking."},
      {"That %race% %class% by the fountain — is that really %item%?", "Glows like Teldrassil at moonrise. Has to be.", "Earned it off %boss%, I heard. %difficulty%, no deaths.", "...I need to sit down. Some people just live a different life.", "Buy them a drink at the Lion's Pride. Greatness rubs off, they say.", "Nothing's ever rubbed off on you but ale stains.", "And I wear them with pride."},
      {"Best corner of the Alliance to watch %weather% roll in?", "The Stormwind canals. Rain on the water, lamps coming on one by one.", "The high terraces of Darnassus. You're above the clouds half the time.", "Ironforge — you don't watch the weather, you escape it by the Great Forge.", "The Exodar crystals catch storm-light like nothing else in the world.", "...all of you, romantics, the lot of you.", "It's a %season% evening and there's a war on. Let us have the small beauties.", "Fair. To small beauties, then. And to surviving long enough to notice them."},
    },
  },

  horde = {
    -- standalone one-liners (single speaker)
    lines = {
      "Valley of Strength is roaring today. Half the Horde came to gawk at the new recruits.",
      "The Drag smells of leather and smoke and something I'd rather not name. Home sweet home.",
      "Down in the Cleft of Shadow the warlocks are at it again. Whole tunnel reeks of brimstone.",
      "Garrosh's banners are everywhere now. The old guard mutters, but quietly.",
      "Zeppelin to the Undercity is late again. Goblin pilot says it's 'weather.' There is no weather up there.",
      "The Valley of Honor forges never sleep. Neither do the smiths, apparently.",
      "Grommash Hold is busy. When the Warchief calls a meeting, the whole city listens at the door.",
      "The wind on the rises of Thunder Bluff carries the smell of sage and open plains. Peace, finally.",
      "Watched the sun set over Mulgore from the highest rise. The tauren were right to settle here.",
      "Spirit Rise is quiet today. Even the totems seem to be listening for something.",
      "The Apothecarium's fumes are thick today. The Forsaken are brewing something that bubbles green.",
      "Undercity's canals run with things best left unexamined. The Forsaken call it 'ambiance.'",
      "A Forsaken bard played a dirge in the Trade Quarter. Saddest thing I've heard. Tipped him double.",
      "The Royal Quarter is colder than the grave. Fitting, given the tenants.",
      "Dark Rangers patrol the upper ring tonight. The Banshee Queen takes no chances.",
      "Silvermoon City gleams red and gold even at midnight. The blood elves spare no expense on beauty.",
      "The Royal Exchange is bustling. Blood elves haggle like it's an art form, because to them it is.",
      "Magisters arguing in Murder Row again. Yes, that's really what the street is called.",
      "A sin'dorei tailor offered to fix my robes. Now I'm too well-dressed to fight anything.",
      "Someone's lost a pet hawkstrider near the bank. Answers to 'Sparkles.' Reward offered, dignity not included.",
      "A Forsaken and a human stood at the same grave in Duskwood. Some losses don't pick a side.",
      "Took the zeppelin from Orgrimmar to the Undercity. Goblin pilot did a loop 'for fun.' I did not have fun.",
      "Spent the afternoon in Silvermoon just looking at the architecture. Felt underdressed the entire time.",
      "Thunder Bluff at dawn, Undercity at dusk. The Horde lands have a beauty the maps never capture.",
      "Summer heat in Orgrimmar is no joke. Even the orcs are seeking shade in the Drag today.",
      "Thunder over Thunder Bluff. On the nose, I know, but the tauren love it.",
      "The Cleft of Shadow gives me the creeps and I'm a warlock. That's saying something.",
      "Valley of Wisdom is where the old shaman gather. Walk soft and listen; they've earned their silence.",
      "The Pools of Vision in Thunder Bluff reflect the sky so clearly you forget which way is up.",
      "My hawkstrider knocked over a fruit cart in Silvermoon. The vendor charged me for 'street theater.'",
      "Trying to park my kodo by the Orgrimmar bank. Got a ticket. From a goblin. With a straight face.",
      "Say what you will about Orgrimmar, but watching the sun rise over those iron walls stirs something in the blood.",
      "Thunder Bluff doesn't conquer; it abides. There's a strength in that the warmongers never understand.",
      "Silvermoon rebuilt itself from ruin into the most beautiful city on Azeroth. Spite never looked so elegant.",
      "The Undercity is a tomb that learned to live. Grim, yes. But the Forsaken made a home where there was only grief.",
      "Word from Orgrimmar: the Warchief's recruiting for a march north. The old veterans sharpen their axes and say nothing.",
      "Gathering a war-band at the Orgrimmar gates for a strike on %instance%. Bring steel and a strong stomach.",
      "Anyone at the Thunder Bluff rise want to ride out to %zone%? The plains are calling and the city's too loud.",
      "A %race% %class% rode through the Valley of Strength on %mount% with %item% strapped to their back. Even the grunts stopped to %emote%.",
      "Word from the front: someone put %boss% in the dirt at %difficulty% and lived to brag about it in the Drag.",
      "LFM %instance% %difficulty% mustering at the Orgrimmar gates. Need a %role%, %gearscore%+, and bring your own %consumable%.",
      "The %profession% master in the Valley of Honor wants %gold% just to teach me %item%. The Earth Mother gives; the trainers most certainly take.",
      "Hit exalted with %rep% this %timeofday%. The quartermaster handed over the %mount% like it was nothing. Lok'tar earned, mon.",
      "Some %level% %class% wandered into the Cleft of Shadow asking for directions to %zone%. The warlocks just... smiled. Poor fool.",
      "A Forsaken hunter dragged %rare% back from %zone% to mount on the wall. The Apothecarium offered to 'preserve' it. She declined, wisely.",
      "%weather% over the Barrens on %route% this %timeofday%. The wind riders are grounded and the caravan masters are furious.",
      "Heard a veteran in Grommash Hold carries the title '%pvptitle%'. Earned it the only way the Horde respects — in blood.",
      "Bard in the Undercity sang of %tale% till the whole Trade Quarter went still. Even the Forsaken remembered how to mourn.",
    },
    -- two-person back-and-forth (speakers alternate A / B)
    duos = {
      {"Why does every orc in Orgrimmar look like they could bench-press a kodo?", "Because most of us can.", "The kodos volunteer. It's a status thing."},
      {"How do you not fall off Thunder Bluff? It's all cliffs and rope bridges.", "We don't look down. The Earth Mother handles the rest."},
      {"Does it ever bother you that the Undercity used to be Lordaeron's crown jewel?", "Every single day. That's rather the point."},
      {"Everything in Silvermoon is so perfect it's almost unsettling.", "Ten thousand years of refinement, darling. Try to keep up."},
      {"The Warchief's banners went up overnight. All of them.", "Garrosh doesn't do subtle.", "...think the old guard will say anything?", "Quietly. Always quietly. That's how you keep your head."},
      {"A shaman told me the elements are angry lately.", "Aye. The earth's been restless under Orgrimmar for weeks.", "Omen?", "Or the forges. Hard to say. The old ones say omen. I'd listen to the old ones."},
      {"Caught a Forsaken laughing in the Apothecarium today.", "Now THAT'S unsettling. What was so funny?", "Didn't ask. Some questions you don't want answered in the Undercity.", "Wise. Very wise."},
      {"That %race% %class% in the Valley of Strength is carrying %item%.", "Off %boss%, at %difficulty%. Earned it in blood.", "...and I'm still hauling ore for %gold% a stack. The Earth Mother tests us all differently."},
      {"%weather% grounded the wind riders again.", "So we take %route%?", "In this %season%? We drink at %shop% till it clears, mon. The Barrens isn't going anywhere."},
      {"Hit exalted with %rep% this %timeofday%.", "The %mount%?", "Mine at last. And every %profession% pattern they were hoarding. Lok'tar, it was worth the grind."},
    },
    -- group discussions (many voices, rotating cast of 4-6)
    groups = {
      {"Which Horde city actually feels like home to you?", "Orgrimmar. Iron walls, hot forges, and the sunrise over the gates. Nothing like it.", "Thunder Bluff. Open sky, clean wind, totems humming. The plains heal you.", "Silvermoon, obviously. Beauty rebuilt from ash. We earned every gilded arch.", "The Undercity. I know, I know. But the Forsaken made a home out of nothing. That means something.", "Sen'jin and the echoes of the islands, for me. The drums still call us, mon.", "...the orc and the tauren are about to argue forges versus plains again, aren't they?", "We always do. And we always end up drinking together after.", "That's the Horde, isn't it. Different blood, same fire.", "Lok'tar. To home, whatever shape it takes."},
      {"War-band's short for %instance% %difficulty%.", "Short what?", "A %role% and a %class% who won't bolt when %boss% enrages.", "%gearscore% here, and I've %consumable% enough for the lot of you.", "Then strap in. We ride from the Orgrimmar gates at %timeofday%. Lok'tar."},
      {"Is %rep% worth the grind, honestly?", "The %mount% at exalted is worth more than %gold% to a Silvermoon collector, so aye.", "And the %profession% patterns. You'll not find %item% taught anywhere else.", "Then it's settled. Dailies at dawn till the quartermaster knows my name.", "He'll know it. He knew mine before I knew the way back to Orgrimmar."},
      {"That %race% %class% in the Drag is carrying %item%, I swear it.", "Off %boss%? At %difficulty%?", "Glows like Silvermoon at midnight. Has to be real.", "Or the best forgery a goblin ever sold. Half the Drag is forgeries.", "...only one way to know. Buy them a drink and ask.", "In the Drag? You buy a stranger a drink, you wake up missing a kidney, mon.", "...fair. We admire from a safe distance, then."},
      {"Best place in the Horde to watch %weather% come in?", "The high rises of Thunder Bluff. You're up in it before it ever touches the plain.", "The Orgrimmar walls at %timeofday%. Iron and storm-light, nothing finer.", "The spires of Silvermoon. Even a downpour looks like a painting from up there.", "...the Undercity. No weather at all. That IS the appeal, for some of us.", "Leave it to the Forsaken to call 'no sky' a feature.", "We made peace with the dark a long time ago. You'd be surprised how restful it is.", "To each their own horizon, then. Drinks in the Valley of Honor after?", "Lok'tar. First round's on the one who said Undercity."},
    },
  },

}
