#!/usr/bin/env python3
"""
Regenerate meta/chatter.manifest.md -- a lightweight index of the chatter file so
agents/tooling can reason about it WITHOUT loading the 300KB+ source into context.

Usage:  python3 tools/gen_manifest.py        (run from the AzerothChatter/ module dir)

Emits aggregate structure only (pool/sub-pool counts, entry-shape tallies, the
%token% vocabulary, and line ranges) -- never the chatter text itself.
Requires: pip3 install lupa --break-system-packages
"""
import os, re, sys
from lupa import LuaRuntime

HERE = os.path.dirname(os.path.abspath(__file__))      # AzerothChatter/tools
ROOT = os.path.dirname(HERE)                           # AzerothChatter
SRC = os.path.join(ROOT, "data", "chatter.lua")
ENGINE = os.path.join(ROOT, "logic", "chatter.lua")    # holds tokenResolvers
OUT = os.path.join(ROOT, "meta", "chatter.manifest.md")

# Tokens the engine resolves but that take no chatter authoring to be valid
# (speaker-derived pronouns, etc.) -- listed so the orphan check below knows they
# are intentional even if no chatter line happens to use them yet.
PRONOUN_TOKENS = {"heshe", "himher", "hisher", "manwoman"}
# Chain-only address tokens: meaningful only in duos/groups, fall back to a vocative
# elsewhere, and may not be used by any chatter line yet -- whitelisted like pronouns.
CHAIN_TOKENS = {"target", "targetfull"}
WHITELIST = PRONOUN_TOKENS | CHAIN_TOKENS

text = open(SRC, encoding="utf-8").read()
lines_total = text.count("\n") + 1
bytes_total = len(text.encode("utf-8"))

lua = LuaRuntime(unpack_returned_tuples=True)
M = lua.execute(text)
ltype = lua.eval("type")

FACTIONS = ["shared", "alliance", "horde"]
SUBPOOLS = ["lines", "duos", "groups"]


def count(tbl):
    return int(lua.eval("function(t) return #t end")(tbl)) if tbl is not None else 0


# %token% vocabulary + tag-key vocabulary, scanned over the raw source.
tokens = sorted(set(re.findall(r"%[a-zA-Z]+%", text)))
tag_keys = sorted(set(re.findall(
    r"\b(roles|moods|genders|areas|times|seasons|events|eventWindow|"
    r"notTimes|notSeasons|notEvents|weight|cooldown|chain)\b\s*=", text)))

# Orphan-token check: cross-reference tokens USED in chatter against the
# tokenResolvers table in logic/chatter.lua (the source of truth for what the
# engine can substitute). Keeps both sides honest -- a chatter %token% with no
# resolver renders literally; a resolver with no use is harmless but flagged.
engine = open(ENGINE, encoding="utf-8").read()
resolver_block = re.search(r"tokenResolvers\s*=\s*{(.*?)\n}", engine, re.S)
resolver_tokens = set()
if resolver_block:
    body = resolver_block.group(1)
    # Strip inline `function(...) ... end` bodies so their local `g =` / comparisons
    # don't masquerade as resolver keys. Two resolvers are packed per line, so we
    # then match every remaining `name =` key (not just the line-initial one).
    body = re.sub(r"function\s*\(.*?\bend\b", "", body, flags=re.S)
    for m in re.finditer(r"([a-zA-Z]\w*)\s*=(?!=)", body):
        resolver_tokens.add(m.group(1))
resolver_tokens |= WHITELIST                            # belt-and-suspenders
used_tokens = {t.strip("%") for t in tokens}
unresolved = sorted(used_tokens - resolver_tokens)      # used in chatter, no resolver
unused = sorted(resolver_tokens - used_tokens - WHITELIST)  # resolver, never used
if unresolved:
    print(f"  WARNING: {len(unresolved)} chatter token(s) with no resolver: "
          + " ".join(f"%{t}%" for t in unresolved), file=sys.stderr)

# Per-pool line ranges: find `<faction> = {` then its `lines/duos/groups = {`.
ranges = {}
src_lines = text.split("\n")
for i, ln in enumerate(src_lines, 1):
    m = re.match(r"\s*(shared|alliance|horde)\s*=\s*{", ln)
    if m:
        ranges.setdefault(m.group(1), i)

rows = []
totals = {sp: 0 for sp in SUBPOOLS}
for fac in FACTIONS:
    pool = M[fac]
    row = {"faction": fac}
    for sp in SUBPOOLS:
        n = count(pool[sp]) if ltype(pool) == "table" else 0
        row[sp] = n
        totals[sp] += n
    rows.append(row)

grand = sum(totals.values())

with open(OUT, "w", encoding="utf-8") as f:
    w = f.write
    w("# data/chatter.lua — chatter manifest\n\n")
    w("> Auto-generated by `tools/gen_manifest.py`. Do not edit by hand.\n")
    w("> Lets you reason about the chatter pools without loading the source file.\n\n")
    w(f"- Source: `data/chatter.lua` — **{lines_total} lines, "
      f"{bytes_total:,} bytes (~{bytes_total//1024} KB)**\n")
    w(f"- Returns a table with three faction pools, each `{{ lines, duos, groups }}`.\n")
    w(f"- **{grand} entries total** "
      f"({totals['lines']} lines, {totals['duos']} duos, {totals['groups']} groups).\n\n")

    w("## Entry counts by pool\n\n")
    w("| Faction | lines | duos | groups | approx. start line |\n")
    w("|---|--:|--:|--:|--:|\n")
    for row in rows:
        w(f"| {row['faction']} | {row['lines']} | {row['duos']} | "
          f"{row['groups']} | {ranges.get(row['faction'], '?')} |\n")
    w(f"| **total** | **{totals['lines']}** | **{totals['duos']}** | "
      f"**{totals['groups']}** | |\n\n")

    w("## %token% vocabulary\n\n")
    w("Tokens substituted at render time by `renderTokens` in `logic/chatter.lua`:\n\n")
    w("".join(f"`{t}` " for t in tokens) + "\n\n")
    w("`%target%` / `%targetfull%` are **chain-only** (duos/groups): they name another\n"
      "cast member (`%target%` a varied short form, `%targetfull%` the full name) and\n"
      "fall back to a neutral vocative ('friend', 'traveler', …) when used outside a\n"
      "chain, so they never render literally. They may not appear above until chatter\n"
      "uses them.\n\n")

    w("## Line-tag keys in use\n\n")
    w("Authoring tags found on entries (parsed by `makeItem`):\n\n")
    w("".join(f"`{k}` " for k in tag_keys) + "\n\n")

    w("## Editing without burning context\n\n")
    w("- Add/edit chatter: open `data/chatter.lua` directly — it's the only place lines live.\n")
    w("- Token logic lives in `logic/chatter.lua` (`renderTokens`); tags are parsed by `makeItem`.\n")
    w("- After editing, rerun `python3 tools/gen_manifest.py` to refresh this file.\n")

print(f"Wrote {OUT}")
print(f"  {grand} entries | lines={totals['lines']} duos={totals['duos']} "
      f"groups={totals['groups']} | {len(tokens)} tokens")
print(f"  resolvers={len(resolver_tokens)} | unresolved={len(unresolved)} "
      f"| unused={len(unused)}")
